version: "3"

services:
  core:
    container_name: flagbase-core
    image: cosmtrek/air
    working_dir: /go/src/github.com/flagbase/flagbase/core
    ports:
      - 5051:5051
      - 7051:7051
      - 9051:9051
    environment:
      FLAGBASE_CORE_PG_URL: user=flagbase password=BjrvWmjQ3dykPu database=flagbase host=db port=5432
      FLAGBASE_CORE_REDIR_ADDR: redis:6379
      FLAGBASE_CORE_REDIS_PASSWORD: ""
      FLAGBASE_CORE_REDIS_DB: 0
    volumes:
      - ./:/go/src/github.com/flagbase/flagbase/core
    depends_on:
      - db
      - migrations
    links:
      - db

  redis:
    container_name: flagbase-cache
    image: redis:latest
    ports:
      - 6380:6379

  db:
    container_name: flagbase-db
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: flagbase
      POSTGRES_USER: flagbase
      POSTGRES_PASSWORD: BjrvWmjQ3dykPu
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flagbase"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    container_name: flagbase-migrations
    build: .
    command: manage migrate up
    environment:
      FLAGBASE_CORE_PG_URL: postgres://flagbase:BjrvWmjQ3dykPu@db:5432/flagbase?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

volumes:
  pgdata:
