name: ci-flagbase-core

on:
  pull_request:
    branches:
      - master
    paths:
      - 'core/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Build
        run: go build -race ./cmd/flagbased/
        working-directory: ./core

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Run tests
        run: go test  ./... -v -covermode=count -coverprofile=coverage.txt
        working-directory: ./core
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CORE_CODECOV_TOKEN }}
          file: ./core/coverage.txt

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.51.2
          working-directory: core
          args: --config=.golangci.yml --timeout 5m
