name: release-flagbase-website

on:
  push:
    branches:
      - main
    paths:
      - 'website/**'
      - 'core/api/swagger/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FLAGBASE_COM_ACCESS_TOKEN }}
          repository: ${{ secrets.FLAGBASE_COM_REPO }}
          event-type: release-website
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
