name: release-flagbase-core

on:
  push:
    branches:
      - main
    paths:
      - 'core/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: ./core
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/core:latest
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FLAGBASE_COM_ACCESS_TOKEN }}
          repository: ${{ secrets.FLAGBASE_COM_REPO }}
          event-type: release-core
