name: release-flagbase-client

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FLAGBASE_COM_ACCESS_TOKEN }}
          repository: ${{ secrets.FLAGBASE_COM_REPO }}
          event-type: release-client
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
